# Generated by Django 4.2a1 on 2023-12-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_support', '0002_post_age_post_country_post_ddx1_post_ddx2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='pic1',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pic2',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pic3',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
