# Generated by Django 5.0 on 2024-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_support', '0007_alter_post_pic2_alter_post_pic3'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ddx1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comments',
            name='ddx2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comments',
            name='provdx',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comments',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
